platform :ios, ‘9.0’
target 'June_nine_BuDeJie' do
	pod 'AFNetworking', '>= 3.1.0'
	pod 'MJExtension', ‘>= 3.0.13'
	pod 'SDWebImage', ‘~> 3.7.5’
	pod 'SVProgressHUD', ‘>= 2.1.2'
	pod ‘MJRefresh’,’>= 3.1.12’
	pod ‘FMDB’,’>=2.7.2’
	pod ‘CTAssetsPickerController’,’>=3.3.2-alpha’
	pod ‘ZFPlayer’, ‘~>2.1.5’
	pod ‘pop’,’~>1.0.10’
end